# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZO2nyty8xz2-6RbBcwlGNCbf5D0FC35O
"""

!pip install essential_generators

import json
import random
from essential_generators import DocumentGenerator

f = open("SMBUD.json")
data = json.load(f)


gen = DocumentGenerator()
#print(gen..sentence())

sections_struct = []
sections_struct.append([{"type": "title"}, {"type": "text"}, {"type":"figure"}])
sections_struct.append([{"type": "title"}, {"type": "text"}, {"type": "subsection", "sections": [{"type": "title", "text": "Subtitle"}, {"type": "text", "text": "Text of a subsection."}]}])
sections_struct.append([{"type": "title"}, {"type": "text"}])
sections_struct.append([{"type": "title"}, 
                        {"type": "subsection", "sections": [
                            {"type": "title", "text": "Subtitle 1"}, 
                            {"type": "text", "text": "Text of a subsection 1."},
                            {"type": "title", "text": "Subtitle 2"}, 
                            {"type": "text", "text": "Text of a subsection 2."}
                            ]},
                        {"type": "figure"}
                        ])
sections_struct.append([{"type": "title"},
                        {"type": "text"},
                        {"type": "subsection", "sections": [
                            {"type": "title", "text": "Subtitle"},
                            {"type": "figure", "url": "https://dummy-image.com/23230.png", "caption": "Caption 1"},
                            {"type": "figure", "url": "https://dummy-image.com/23240.png", "caption": "Caption 2"}
                        ]}
])

def generateSection(index):
  a = sections_struct[index]
  for j in a:
    if(j['type'] == "title"):
      j['text'] = gen.sentence()
    if(j['type'] == "text"):
      j['text'] = gen.sentence() + ". " + gen.sentence() + ". " + gen.sentence() + ". " + gen.sentence()
    if(j['type'] == "figure"):
      j['url'] = "https://dummy-image.com/" + str(random.randint(100,300)) + ".png"
      j['caption'] = gen.sentence()
  return a

def generateBib(total):
  output = []
  for i in range(0, total):
    output.append(data[random.randint(0, 1499)]['_id'])
  return output

for i in data:
  i['sections'] = generateSection(random.randint(0, 4))
  if(random.randint(0, 10)):
    i['bibliography'] = generateBib(random.randint(1, 3))

f = open('output2.json', 'w')
json.dump(data, f)